// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw-tDMjiBnkTe4HGSW-gxtDqpRRNSmPKo',
    appId: '1:756622070669:web:d46aafe0206281cdafe3c4',
    messagingSenderId: '756622070669',
    projectId: 'fir-app1-61c34',
    authDomain: 'fir-app1-61c34.firebaseapp.com',
    storageBucket: 'fir-app1-61c34.appspot.com',
    measurementId: 'G-7RQXNT7LGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9KLP8PEug-N2hgLCsQn_P6HWHGzNKCao',
    appId: '1:756622070669:android:909bc858dc14b5f0afe3c4',
    messagingSenderId: '756622070669',
    projectId: 'fir-app1-61c34',
    storageBucket: 'fir-app1-61c34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS22UNRtqe8Qp7bsuv3B5_6POTtUTB-tY',
    appId: '1:756622070669:ios:f7f8da8a1e45cfbcafe3c4',
    messagingSenderId: '756622070669',
    projectId: 'fir-app1-61c34',
    storageBucket: 'fir-app1-61c34.appspot.com',
    iosClientId: '756622070669-si440snl2pk470te252njn0pcesunvib.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushNotificationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS22UNRtqe8Qp7bsuv3B5_6POTtUTB-tY',
    appId: '1:756622070669:ios:b7e8912a45ffb951afe3c4',
    messagingSenderId: '756622070669',
    projectId: 'fir-app1-61c34',
    storageBucket: 'fir-app1-61c34.appspot.com',
    iosClientId: '756622070669-h6hnneq264sij5ftssqr2k7k4f6ob3ds.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushNotificationApp.RunnerTests',
  );
}
